# Generated by Django 3.1 on 2020-09-08 11:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200907_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('onjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
