# Generated by Django 3.1 on 2020-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sku',
        ),
        migrations.AlterField(
            model_name='course',
            name='excerpt',
            field=models.TextField(default='some string', max_length=50),
        ),
    ]
